# Generated by Django 4.0 on 2023-08-20 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah_name', models.TextField()),
                ('surah_uid', models.IntegerField()),
                ('surah_type', models.TextField()),
                ('number_of_ayahs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LeaderboardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Ayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('number', models.IntegerField()),
                ('audio', models.TextField(default='')),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.surah')),
            ],
        ),
    ]
