# Generated by Django 4.0 on 2023-08-20 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surah',
            name='surah_uid',
        ),
    ]
