# Generated by Django 4.0 on 2023-08-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sessionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionmodel',
            name='audio',
            field=models.URLField(default=''),
        ),
    ]
